### ISSUE TITLE
PCQI =Inf?

### ISSUE THREAD

**Issue by Spacei567** [666ShuqiWang/Multi-weight-and-Multi-granularity-Fusion-of-Underwater-Image-Enhancement#1]

**Comment by Spacei567** [comment]
I know.  The size of pictures must be same

**Comment by 666ShuqiWang** [comment]
Sorry.&nbsp;I don't know what you're talking about. Please describe the problem more clearly.



发自我的iPhone


------------------ Original ------------------
From: Spacei567 ***@***.***&gt;
Date: Sat,Nov 12,2022 11:20 PM
To: 666ShuqiWang/Multi-weight-and-Multi-granularity-Fusion-of-Underwater-Image-Enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [666ShuqiWang/Multi-weight-and-Multi-granularity-Fusion-of-Underwater-Image-Enhancement] PCQI =Inf? (Issue #1)





 
I know.  The size of pictures must be same
